/**
 * The spec-and-compiled-SQL pairing for "The artifact".
 *
 * Both halves are excerpts of files portia actually wrote, on 2026-08-11,
 * against portia @ 1fa5a81, in `portia/sandbox/www-demo`. To regenerate:
 *
 *     python -m portia.cli.run   specs/hotel_daily_demand.yaml --write out
 *     python -m portia.cli.build
 *
 * They are excerpts, and the page says which kind of edit each one carries.
 *
 *   - **The spec is verbatim.** Its rationales are wrapped at ~50 columns in
 *     the file itself rather than re-wrapped here, precisely so this can be a
 *     copy rather than a rendering. A folded YAML scalar's line breaks are not
 *     part of its value, so narrowing them upstream changed nothing.
 *   - **The model is elided and re-broken.** `…` marks text taken out; and
 *     `pipeline.py` emits each CTE's whole projection on one line, so the final
 *     SELECT is broken across lines here to fit a 480px column. That is a
 *     reflow, not a quote, and the caption on the page says so.
 */

export const specFile = "specs/hotel_daily_demand.yaml";

export const specExcerpt = `  - id: events_daily
    op: sql
    inputs: [clean_events]
    sql: >-
      SELECT city_name, event_date, count(*) AS n_events,
             sum(expected_attendance) AS expected_attendance
      FROM clean_events
      GROUP BY city_name, event_date
    rationale: >-
      Aggregate before joining. city_events has two
      events in Amsterdam on one day and two in
      Barcelona; joined raw, each fans a booking into
      two rows and doubles its revenue. One row per
      city-date is what a booking joins to.
    grain: [city_name, event_date]

  - id: hotel_daily_demand
    op: join
    left: bookings_with_hotel
    right: events_daily
    left_on: [city, stay_date]
    right_on: [city_name, event_date]
    how: left
    grain: [booking_id]
    rationale: >-
      Two hops: otb knows only hotel_id and has no
      city, so hotels is the only bridge to
      city_events. left join keeps every booking
      whether or not anything was happening in its
      city that day.
    expect:
      result_rows: 14`;

export const modelFile = "models/hotel_daily_demand.sql";

export const modelExcerpt = `-- hotel_daily_demand — generated by portia. Do not edit.
-- Change specs/hotel_daily_demand.yaml and regenerate; …
-- generated 2026-08-11T10:12:28
-- spec fingerprint 05fec60

CREATE TABLE "hotel_daily_demand" AS
WITH "strip_event_city" AS (…),
"clean_events" AS (…),
"clean_hotels" AS (…),
"events_daily" AS (
    SELECT city_name, event_date, count(*) AS n_events,
           sum(expected_attendance) AS expected_attendance
    FROM clean_events GROUP BY city_name, event_date
),
"bookings_with_hotel" AS (…),
"hotel_daily_demand" AS (
    SELECT l."booking_id" AS "booking_id", …
    FROM "bookings_with_hotel" AS "l"
    LEFT JOIN "events_daily" AS "r"
      ON l."city" = r."city_name"
     AND l."stay_date" = r."event_date"
)
SELECT * FROM "hotel_daily_demand";`;
